general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 12.0

[terminal.shell]
program = "zellij"
args = ["-l", "welcome"]

[window]
startup_mode = "Maximized"
option_as_alt = "Both"
